services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rsupport
      MYSQL_DATABASE: notice
      MYSQL_USER: rsupport
      MYSQL_PASSWORD: rsupport
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  redis_data:
  mysql_data: