server:
  port: 8080

spring:
  application:
    name: kyusubkim-20250501
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/notice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: rsupport
    password: rsupport
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    redisson:
      config:
        singleServerConfig:
          address: "redis://localhost:6379"
